services:
  - type: web
    name: video-stitcher
    env: python
    buildCommand: |
      # Install latest FFMPEG
      apt-get update && apt-get install -y software-properties-common
      add-apt-repository ppa:jonathonf/ffmpeg-4
      apt-get update && apt-get install -y ffmpeg
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn api.wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: MAX_FILE_SIZE_MB
        value: 100
      - key: MAX_CONCURRENT_PROCESSES
        value: 2
      - key: MAX_QUEUE_SIZE
        value: 10
      - key: MAX_RECENT_JOBS
        value: 50
      - key: MAX_FILE_AGE_HOURS
        value: 24
      - key: DEFAULT_WWE_VIDEO
        value: /opt/render/project/src/wwe_video.mp4
    healthCheckPath: /api/status
    disk:
      name: video-storage
      mountPath: /tmp
      sizeGB: 10 