services:
  - type: web
    name: video-stitcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: RENDER_TEMP_DIR
        value: /tmp
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /tmp/uploads
      sizeGB: 10
    disk:
      name: outputs
      mountPath: /tmp/outputs
      sizeGB: 10 